spring:
  application:
    name: "Text Blaster Redux"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${googleClientId}
            clientSecret: ${googleClientSecret}
            scope:
              - email
              - profile
admin:
  phoneNumber: ${adminPhone}
  email: ${adminEmail}

twilio:
  accountSid: ${twilioAccountSid}
  authToken: ${twilioAuthToken}
